### ISSUE TITLE
Regarding mocking

### ISSUE THREAD

**Issue by vinayganesh** [bartvandeweerdt/hello-reliant#1]
How exactly do you mock your service ? according to what you said here

"In a unit testing scenario where you'd like your tested class to call a mock service instead of the real service."

**Comment by bartvandeweerdt** [comment]
Hi,
Since the service is injected in your tested class, you can inject any implementation during the 'setup' of your unit test. This could be anything that implements the service's protocol (e.g. _UnfriendlyGreeter_ implements the _Greeter_ protocol). Or you can use something like [OCMockito](https://github.com/jonreid/OCMockito), [mock the protocol](https://github.com/jonreid/OCMockito#how-do-you-mock-a-protocol) and inject that. Hope this answers your question.
